# Created using wingetcreate 1.0.4.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.1.0.schema.json

PackageIdentifier: KPN.KPNInContact
PackageVersion: 22.9.30.235
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.1.0

